# pytest.ini
[pytest]
addopts = -v
testpaths = Task_1/tests

markers =
    test_burger: Тесты для файла burger.py
    test_bun: Тесты для файла bun.py
    test_ingredient: Тесты для файла ingredient.py
    test_database: Тесты для файла database.py